---
name: Codespell

on:
  push:
    branches: [master,hypernext]
  pull_request:
    branches: [master,hypernext]

jobs:
  codespell:
    name: Check for typos
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run codespell
        uses: codespell-project/actions-codespell@v1
