name: Push images of new releases to Docker Hub

on:
    push:
        tags:
           - '*'

jobs:
    buildandpush:
        runs-on: ubuntu-latest
        steps:
            - name: Get the current elabftw version tag from Dockerfile
              id: latesttag
              run: |
                echo "::set-output name=tag::$(curl -s https://raw.githubusercontent.com/elabftw/elabimg/master/Dockerfile | grep ELABFTW_VERSION | head -n 1 | rev | cut -d= -f1 | rev)"

            - name: Verify release tags
              run: |
                  echo ${{ steps.latesttag.outputs.tag}}

            - name: Checkout elabimg repo on latest tag
              uses: actions/checkout@v2
              with:
                  repository: "elabftw/elabimg"
                  ref: ${{ steps.latesttag.outputs.tag }}

            # https://github.com/docker/setup-qemu-action#usage
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            # https://github.com/marketplace/actions/docker-setup-buildx
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            # https://github.com/docker/login-action#docker-hub
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_TOKEN }}

            # https://github.com/docker/build-push-action#multi-platform-image
            - name: Build latest release for all platforms and push to Docker Hub
              uses: docker/build-push-action@v2
              with:
                context: .
                platforms: linux/arm64,linux/amd64
                push: true
                tags: |
                    elabftw/elabimg:latest
                    elabftw/elabimg:${{ steps.latesttag.outputs.tag }}
